### ISSUE TITLE
User accounts accrue RAM

### ISSUE THREAD

**Issue by choldgraf** [data-8/interact#22]
This is going to be a tough one to debug, but I noticed that many students in our exam were accruing RAM that seemed to persist after restarting kernels. Basically they would have one jupyter notebook running, and would be maxing out RAM, and after they restarted the kernel there would still be like 1GB of ram taken up.

I made sure they didn't have any other notebooks open, and the only thing that would resolve the problem was to shut down their data8 server, and then restart it.

Has anybody else reported this kind of thing? Any ideas what might be going on?

**Comment by ryanlovett** [comment]
It does sound perplexing. If the kernel isn't running then the notebook's
data objects shouldn't be loaded yet.

We can potentially post a metric of each notebook's individual memory usage
to complement the user's server memory usage.

If this happens again, can you please open a notebook terminal, run 'top',
then type 'M' to sort by memory? If one process is consuming most of the
memory, please let us know the output of 'cat /proc/${pid_of_nefarious_
process}/cmdline'.

This isn't an interact bug though; probably should be in data-8/systemuser.

Ryan

**Comment by choldgraf** [comment]
Oops, didn't realize I opened this in the interact section. Want me to open an issue there and close this?

**Comment by ryanlovett** [comment]
No worries. That'd be great if you could close and reopen.

Ryan

**Comment by choldgraf** [comment]
closed in favor of https://github.com/data-8/systemuser/issues/1
