### ISSUE TITLE
Rename this extension

### ISSUE THREAD

**Issue by ryanlovett** [data-8/interact#24]
This extension was named after the INTERACT button labels of the inferentialthinking.com textbook, but doesn't convey this extension's purpose. There's also "nteract" in the notebook-verse namespace.

Suggestions:
- nbimport
- nbfetch
- nbpull
- nbclone

**Comment by yuvipanda** [comment]
Did this happen? What name was decided on? I'm personally partial to 'nbgitpull' since that's very accurate, and if not that than 'nbpull'. nbimport already exists, hooking up notebooks into python's import machinery.

**Comment by ryanlovett** [comment]
No, ages ago it was "interact" and a few months ago it was renamed to "nbinteract".

I forgot about the initial rename which is why I accidentally posted the issue here.

See https://github.com/data-8/nbinteract/issues/2.
