### ISSUE TITLE
Error on merge overwriting untracked files

### ISSUE THREAD

**Issue by ryanlovett** [data-8/interact#5]
Via Gasper Zaragoza at https://piazza.com/class/ijdg22juvgh64x?cid=489. The issue is actually marked as resolved so I don't know the current status.

> My server was working fine last night but I'm getting this type of error this morning.
> 
>  (error: The following untracked working tree files would be overwritten by merge: labs/hw04/tests/**pycache**/**init**.cpython-35.pyc labs/hw04/tests/**pycache**/q12.cpython-35.pyc labs/hw04/tests/**pycache**/q13.cpython-35.pyc labs/hw04/tests/**pycache**/q15.cpython-35.pyc labs/hw04/tests/**pycache**/q16.cpython-35.pyc labs/hw04/tests/**pycache**/q23.cpython-35.pyc labs/hw04/tests/**pycache**/q25.cpython-35.pyc Please move or remove them before you can merge. Aborting)
> 
> username: gasparzaragoza@berkeley.edu

**Comment by ryanlovett** [comment]
Also Mandy Zhang at https://piazza.com/class/ijdg22juvgh64x?cid=511

> error: The following untracked working tree files would be overwritten by merge: labs/hw04/tests/**pycache**/**init**.cpython-35.pyc labs/hw04/tests/**pycache**/q12.cpython-35.pyc labs/hw04/tests/**pycache**/q13.cpython-35.pyc labs/hw04/tests/**pycache**/q15.cpython-35.pyc labs/hw04/tests/**pycache**/q16.cpython-35.pyc labs/hw04/tests/**pycache**/q23.cpython-35.pyc labs/hw04/tests/**pycache**/q25.cpython-35.pyc Please move or remove them before you can merge. Aborting

**Comment by SamLau95** [comment]
I think this is happening because the .gitignore file isn't being copied over from the data8assets repo.

I fixed this for peiyong.sim by copying over the .gitignore and running

```
git clean -d -fx
```

In her data8assets folder.

**Comment by papajohn** [comment]
Does this issue require a change to the interact server? Basically, should we always try to checkout `.gitignore` even if it isn't one of the requested files?

**Comment by SamLau95** [comment]
That sounds like a good idea.
